baseURL = 'https://wuyuanchao.github.io/'
languageCode = 'en-us'
title = "wuyuanchao's"
theme = 'hugo-book'

[security.exec]
allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
