---
title: "Vim Windows"
date: 2023-03-01T17:39:40+08:00
draft: false
---
== Working With Vim Windows
https://www.baeldung.com/linux/vim-windows

=== Buffers and Windows

*A buffer is a temporary copy of a file’s contents.* When we open a file, Vim loads its contents into memory. The original file remains intact until we save our changes.

Along with the buffer, Vim creates a window through which we do the editing. A window, in essence, is a view of a buffer. Multiple windows can display the same file or buffer.

=== Split Windows 

The main view can be split into multiple windows, both horizontal and vertical.
With the :split, or short :sp, command we can open a new horizontal split window on the current buffer:

----
:sp 
----

With a file path argument, a new split window opens for the specified file. It can be an existing or a new file:

----
:sp {file path}
----

We can also split the current window vertically with the :vsplit, or short :vsp, command.

----
:vsp 
----

----
:vsp {file path}
----


The :new command too has its vertical equivalent. Instead of a horizontal split window, it opens a vertical one on the left side of the active window:

----
:vnew [{file path}]
----

with the -o option followed by a space-delimited list of file paths opens them in horizontally split windows.

----
vim -o {file path 1} {file path 2} ...
----

=== Window Commands

*The Ctrl+w key combination enters us into the window command mode.*

The Ctrl+w +w combination navigates to the next split window and makes it the active one. It wraps around reaching the end.
The Ctrl+w +number +w combination jumps to the n-th window.
Ctrl+w +W works similarly but in the opposite direction.

Ctrl+w +p goes to the previous, last accessed window. Ctrl+w +t goes to the top left and Ctrl+w +b to the bottom right window.


